### ISSUE TITLE
python 3 support broken

### ISSUE THREAD

**Issue by ellisong** [strycore/fakegir#9] opened 2014-06-11 04:31 UTC
Python 3.4 does not work with the current revision

With 'python3 fakegir.py', I get:

Traceback (most recent call last):
  File "fakegir.py", line 230, in <module>
    generate_fakegir()
  File "fakegir.py", line 222, in generate_fakegir
    fakegir_content = parse_gir(gir_path)
  File "fakegir.py", line 191, in parse_gir
    namespace_content = extract_namespace(namespace)
  File "fakegir.py", line 168, in extract_namespace
    docstring)
  File "fakegir.py", line 73, in insert_function
    "\n").split("\n")])
TypeError: can't concat bytes to str

To resolve the issue, I placed a str() around docstring in line 70.

**Comment by r03** [comment] 2017-12-05 10:17
I tried python 3.6 and it works for me. This issue is 3 years old. Maybe just close it?

**Comment by codywd** [comment] 2017-12-06 12:30
Thanks for the info @r03. It's been a while since I've used this.

**Comment by strycore** [comment] 2017-12-06 18:31
Yeah, I've used fakegir recently and with Python 3, guess the issue is fixed.

**Closed by strycore** 2017-12-06 18:31 UTC
