### ISSUE TITLE
Problem with files *.gir

### ISSUE THREAD

**Issue by ErickTucto** [strycore/fakegir#22] opened 2018-06-23 21:36 UTC
The following files do not finish generating

- '/usr/share/gir-1.0/NM-1.0.gir',
- '/usr/share/gir-1.0/Atspi-2.0.gir',
- '/usr/share/gir-1.0/GstCheck-1.0.gir',
- '/usr/share/gir-1.0/GExiv2-0.10.gir',
- '/usr/share/gir-1.0/Dbusmenu-0.4.gir',
- '/usr/share/gir-1.0/HarfBuzz-0.0.gir'

Example `'/usr/share/gir-1.0/NM-1.0.gir',`

![2018_06_23_001](https://user-images.githubusercontent.com/22831024/41813818-dfe45226-7702-11e8-93af-2f4c90604412.png)

I add if statement
```python
def generate_fakegir():
    """Main function"""
    fakegir_repo_dir = os.path.join(FAKEGIR_PATH, 'gi/repository')
    if not os.path.exists(fakegir_repo_dir):
        os.makedirs(fakegir_repo_dir)

    gi_init_path = os.path.join(FAKEGIR_PATH, 'gi/__init__.py')
    with open(gi_init_path, 'w') as gi_init_file:
        gi_init_file.write('')
    repo_init_path = os.path.join(FAKEGIR_PATH, 'gi/repository/__init__.py')
    with open(repo_init_path, 'w') as repo_init_file:
        repo_init_file.write('')

    for module_name, gir_path in iter_girs():
        if gir_path in PASS:
            continue

        fakegir_content = parse_gir(gir_path)
        fakegir_path = os.path.join(FAKEGIR_PATH, 'gi/repository',
                                    module_name + ".py")
        with open(fakegir_path, 'w') as fakegir_file:
            fakegir_file.write("# -*- coding: utf-8 -*-\n")
            fakegir_file.write(fakegir_content)
```

```python
PASS = (
    '/usr/share/gir-1.0/NM-1.0.gir',
    '/usr/share/gir-1.0/Atspi-2.0.gir',
    '/usr/share/gir-1.0/GstCheck-1.0.gir',
    '/usr/share/gir-1.0/GExiv2-0.10.gir',
    '/usr/share/gir-1.0/Dbusmenu-0.4.gir',
    '/usr/share/gir-1.0/HarfBuzz-0.0.gir'
)
```

**Comment by kastixx** [comment] 2018-08-24 21:49
This issue is most probably caused by the same problem as #24

**Comment by kastixx** [comment] 2018-08-25 20:41
There's a workaround in PR #25. Please check if it works for you.

**Comment by kmare** [comment] 2018-08-29 11:50
I had the same problem on Fedora 28. Applied the patch and I can confirm it finally works. Thank you!

**Comment by strycore** [comment] 2018-08-29 15:16
Merged the PR, should be ok now

**Closed by strycore** 2018-08-29 15:16 UTC
